name: Deploy and Run on EC2

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: executing remote ssh commands using key
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script_stop: false
        debug: true
        script: |
          cd /home/ec2-user/controller/cloud_controller
          git pull https://github.com/matt-gregor/cloud_controller.git
          docker build -t cloud_controller:latest .
          docker stop docker_controller && docker rm -fv docker_controller && docker image prune -f || true
          docker run --restart unless-stopped \
          -e ${{ secrets.INFLUXDB_TOKEN }} \
          --detach \
          -p 8080:8080 \
          --name docker_controller \
          --network="communication-network" \
          cloud_controller:latest



